/** Sample clients — seeded into Appwrite via `npm run appwrite:seed-clients`. */

export const MOCK_COMPANIES = [
  {
    id: 'mock-company-medtech',
    name: 'MedTech Lebanon',
    legalName: 'MedTech Lebanon SARL',
    email: 'info@medtech.lb',
    phone: '+9611445566',
    contactPhones: [
      { countryDial: '+961', nationalNumber: '1445566', label: 'Main' },
      { countryDial: '+961', nationalNumber: '70111222', label: 'Mobile' },
    ],
    contactEmails: [{ address: 'info@medtech.lb', label: 'Work' }],
    address: 'Mar Mikhael, Beirut',
    contactAddresses: [
      {
        text: 'Mar Mikhael, Beirut',
        label: 'Head office',
        reference: 'Building 12',
        latitude: 33.8968,
        longitude: 35.5234,
      },
    ],
    industry: 'Healthcare & medical',
    website: 'https://medtech.lb',
    contactWebsites: [
      { url: 'https://medtech.lb', label: 'Main' },
      { url: 'https://support.medtech.lb', label: 'Support' },
    ],
    notes: 'Hospital equipment maintenance contract.',
    primaryContactId: 'mock-person-karim',
  },
  {
    id: 'mock-company-cedar',
    name: 'Cedar Hospitality',
    legalName: 'Cedar Hospitality Group SAL',
    email: 'reservations@cedarhospitality.lb',
    phone: '+9611998877',
    contactPhones: [{ countryDial: '+961', nationalNumber: '1998877', label: 'Work' }],
    contactEmails: [{ address: 'reservations@cedarhospitality.lb', label: 'Work' }],
    address: 'Downtown, Beirut',
    contactAddresses: [{ text: 'Downtown, Beirut', label: 'Head office' }],
    industry: 'Hospitality & tourism',
    website: 'https://cedarhospitality.lb',
    contactWebsites: [
      { url: 'https://cedarhospitality.lb', label: 'Main' },
      { url: 'https://book.cedarhospitality.lb', label: 'Shop' },
    ],
    notes: '',
    primaryContactId: 'mock-person-lina',
  },
  {
    id: 'mock-company-beirut-logistics',
    name: 'Beirut Logistics',
    legalName: 'Beirut Logistics & Warehousing SARL',
    email: 'ops@beirutlogistics.lb',
    phone: '+9611754321',
    contactPhones: [
      { countryDial: '+961', nationalNumber: '1754321', label: 'Main' },
      { countryDial: '+961', nationalNumber: '78901234', label: 'Mobile' },
    ],
    contactEmails: [
      { address: 'ops@beirutlogistics.lb', label: 'Work' },
      { address: 'dispatch@beirutlogistics.lb', label: 'Other' },
    ],
    address: 'Industrial zone, Dora, Metn',
    contactAddresses: [
      {
        text: 'Industrial zone, Dora, Metn',
        label: 'Warehouse',
        latitude: 33.9102,
        longitude: 35.5891,
      },
    ],
    industry: 'Logistics & transport',
    website: '',
    contactWebsites: [],
    notes: 'After-hours access via gate B.',
    primaryContactId: 'mock-person-rami',
  },
  {
    id: 'mock-company-phoenicia-retail',
    name: 'Phoenicia Retail',
    legalName: 'Phoenicia Retail SAL',
    email: 'contact@phoeniciaretail.lb',
    phone: '+9611367788',
    contactPhones: [{ countryDial: '+961', nationalNumber: '1367788', label: 'Work' }],
    contactEmails: [{ address: 'contact@phoeniciaretail.lb', label: 'Work' }],
    address: 'Verdun, Beirut',
    contactAddresses: [{ text: 'Verdun, Beirut', label: 'Branch' }],
    industry: 'Retail & shops',
    website: 'https://phoeniciaretail.lb',
    contactWebsites: [
      { url: 'https://phoeniciaretail.lb', label: 'Main' },
      { url: 'https://shop.phoeniciaretail.lb', label: 'Shop' },
    ],
    notes: '',
    primaryContactId: 'mock-person-nour',
  },
  {
    id: 'mock-company-levant-build',
    name: 'Levant Build Co.',
    legalName: 'Levant Build Company SARL',
    email: 'projects@levantbuild.lb',
    phone: '+9616123456',
    contactPhones: [{ countryDial: '+961', nationalNumber: '6123456', label: 'Mobile' }],
    contactEmails: [{ address: 'projects@levantbuild.lb', label: 'Work' }],
    address: 'Highway site, Jounieh',
    contactAddresses: [{ text: 'Highway site, Jounieh', label: 'Site', reference: 'Phase 2' }],
    industry: 'Construction & contractors',
    website: '',
    contactWebsites: [],
    notes: 'Active site — safety gear required.',
    primaryContactId: 'mock-person-elias',
  },
];

export const MOCK_PERSONS = [
  {
    id: 'mock-person-karim',
    firstName: 'Karim',
    lastName: 'Haddad',
    email: 'karim.haddad@medtech.lb',
    phone: '+96170123456',
    contactPhones: [
      { countryDial: '+961', nationalNumber: '70123456', label: 'Mobile' },
      { countryDial: '+961', nationalNumber: '1445566', label: 'Work' },
    ],
    contactEmails: [{ address: 'karim.haddad@medtech.lb', label: 'Work' }],
    address: 'Mar Mikhael, Beirut',
    contactAddresses: [{ text: 'Mar Mikhael, Beirut', label: 'Head office' }],
    notes: 'Technical director — prefers WhatsApp.',
    companyId: 'mock-company-medtech',
  },
  {
    id: 'mock-person-lina',
    firstName: 'Lina',
    lastName: 'Nasr',
    email: 'lina.nasr@cedarhospitality.lb',
    phone: '+96170987654',
    contactPhones: [{ countryDial: '+961', nationalNumber: '70987654', label: 'Mobile' }],
    contactEmails: [{ address: 'lina.nasr@cedarhospitality.lb', label: 'Work' }],
    address: 'Downtown, Beirut',
    contactAddresses: [{ text: 'Downtown, Beirut', label: 'Head office' }],
    notes: '',
    companyId: 'mock-company-cedar',
  },
  {
    id: 'mock-person-rami',
    firstName: 'Rami',
    lastName: 'Khoury',
    email: 'rami.k@beirutlogistics.lb',
    phone: '+96178901234',
    contactPhones: [{ countryDial: '+961', nationalNumber: '78901234', label: 'Mobile' }],
    contactEmails: [{ address: 'rami.k@beirutlogistics.lb', label: 'Work' }],
    address: 'Industrial zone, Dora, Metn',
    contactAddresses: [{ text: 'Industrial zone, Dora, Metn', label: 'Warehouse' }],
    notes: 'Dispatch lead.',
    companyId: 'mock-company-beirut-logistics',
  },
  {
    id: 'mock-person-nour',
    firstName: 'Nour',
    lastName: 'Frem',
    email: 'nour@phoeniciaretail.lb',
    phone: '+96176889900',
    contactPhones: [{ countryDial: '+961', nationalNumber: '76889900', label: 'Mobile' }],
    contactEmails: [{ address: 'nour@phoeniciaretail.lb', label: 'Work' }],
    address: 'Verdun, Beirut',
    contactAddresses: [{ text: 'Verdun, Beirut', label: 'Branch' }],
    notes: '',
    companyId: 'mock-company-phoenicia-retail',
  },
  {
    id: 'mock-person-elias',
    firstName: 'Elias',
    lastName: 'Mouawad',
    email: 'elias.m@levantbuild.lb',
    phone: '+9616123456',
    contactPhones: [{ countryDial: '+961', nationalNumber: '6123456', label: 'Mobile' }],
    contactEmails: [{ address: 'elias.m@levantbuild.lb', label: 'Work' }],
    address: 'Highway site, Jounieh',
    contactAddresses: [{ text: 'Highway site, Jounieh', label: 'Site' }],
    notes: 'Site supervisor.',
    companyId: 'mock-company-levant-build',
  },
  {
    id: 'mock-person-maya',
    firstName: 'Maya',
    lastName: 'Saade',
    email: 'maya.saade@gmail.com',
    phone: '+96171122334',
    contactPhones: [{ countryDial: '+961', nationalNumber: '71122334', label: 'Mobile' }],
    contactEmails: [
      { address: 'maya.saade@gmail.com', label: 'Personal' },
      { address: 'maya@freelance.lb', label: 'Work' },
    ],
    address: 'Achrafieh, Beirut',
    contactAddresses: [{ text: 'Achrafieh, Beirut', label: 'Home' }],
    notes: 'Freelance HVAC consultant — no company link.',
    companyId: '',
  },
  {
    id: 'mock-person-sami',
    firstName: 'Sami',
    lastName: 'Tannous',
    email: 'sami.tannous@medtech.lb',
    phone: '+96170334455',
    contactPhones: [{ countryDial: '+961', nationalNumber: '70334455', label: 'Mobile' }],
    contactEmails: [{ address: 'sami.tannous@medtech.lb', label: 'Work' }],
    address: 'Mar Mikhael, Beirut',
    contactAddresses: [{ text: 'Mar Mikhael, Beirut', label: 'Head office' }],
    notes: 'Second contact at MedTech.',
    companyId: 'mock-company-medtech',
  },
  {
    id: 'mock-person-rana',
    firstName: 'Rana',
    lastName: 'Gemayel',
    email: 'rana.g@cedarhospitality.lb',
    phone: '+96176554433',
    contactPhones: [{ countryDial: '+961', nationalNumber: '76554433', label: 'Mobile' }],
    contactEmails: [{ address: 'rana.g@cedarhospitality.lb', label: 'Work' }],
    address: 'Downtown, Beirut',
    contactAddresses: [{ text: 'Downtown, Beirut', label: 'Head office' }],
    notes: 'Events coordinator.',
    companyId: 'mock-company-cedar',
  },
];
